---
title: "Characterize DC reference after integration"
author: "Massimo Andreatta & Santiago Carmona"
#output: html_notebook
---

```{r}
renv::restore()
```

Libraries
```{r}
library(ggplot2)
library(Seurat)
library(tidyr)
library(SeuratObject)
library(Matrix)
library(patchwork)
library(remotes)
library(UCell)
library(STACAS)
```

Read in integrated reference
```{r}
pdir <- "~/Dropbox/CSI/Datasets/Gerhard_JEM"

ref <- readRDS(paste0(pdir,"/DC_human_ref_v1.rds"))
palette <- ref@misc$atlas.palette

DimPlot(ref, cols = palette, label=T) + theme(aspect.ratio = 1)
ggsave("plots/DC_reference_umap.pdf", height=4, width=7)
ggsave("plots/DC_reference_umap.png", height=4, width=7)
```
```{r}
p1 <- DimPlot(ref, reduction="umap", group.by="Study") + theme(aspect.ratio = 1)
p2 <- DimPlot(ref, cols = palette, label=T) + theme(aspect.ratio = 1)
p1 | p2

#Save object
ggsave("plots/DC_reference_bysample_noDoub.pdf", height = 5, width=10)
```

```{r fig.height=3.5}
DefaultAssay(ref) <- "RNA"
FeaturePlot(ref, features=c("CD1A","CD207","CLEC10A","FCGBP"))
FeaturePlot(ref, features=c("LAMP3","BIRC3","GZMB","CCR7"))
FeaturePlot(ref, features=c("FCER1A","CD1C","CLEC10A","FCGR2A"))
FeaturePlot(ref, features=c("CD1A","CD207","HLA-DQA1","HLA-DQB1"))
FeaturePlot(ref, features=c("CADM1","XCR1","CD200R1","CD200R1L"))
```


Find markers for subtypes in the reference
```{r}
Idents(ref) <- "functional.cluster"
DefaultAssay(ref) <- "RNA"

set.seed(1234)
cluster.markers <- FindAllMarkers(ref, only.pos = T, min.pct = 0.1, min.diff.pct=0.1, 
                                  logfc.threshold = 0.25, max.cells.per.ident = 500, test.use="wilcox",base=exp(1))

all <- cluster.markers |> dplyr::group_by(cluster) |> dplyr::top_n(n = 50, wt = abs(avg_logFC))

for (i in levels(ref@active.ident)) {
    print(subset(all, cluster==i))
}  
DefaultAssay(ref) <- "integrated"

```

Make a heatmap of DEGs
```{r fig.height=4}
ref.copy <- ref
DefaultAssay(ref.copy) <- 'RNA'
ref.copy <- ScaleData(ref.copy)

genes.use <- c()
for (i in levels(ref.copy$functional.cluster)) {
    this <- as.vector(all[all$cluster==i, "gene"])[[1]]
    this <- this[1:min(8, length(this))]
    
    genes.use <- c(genes.use, this)
}

heat <- DoHeatmap(ref.copy, assay="RNA", features=genes.use, group.by = "functional.cluster", group.colors = palette)

heat + scale_fill_gradientn(colors = c("blue", "white", "red"))
ggsave("plots/DC_scHeatmap_topDEG.png", height=11, width=21)
```


Violin plot of marker genes
```{r fig.height=5, fig.width=3}
DefaultAssay(ref.copy) <- "RNA"

genes <- c("CLEC9A","XCR1","CADM1","CLEC10A","FCGR2A","FCER1A","CD1C","CD1A","CD207",
                 "LAMP3","CCR7","FSCN1","GZMB","LILRA4","TCF4","PPP1R14A","AXL",
           "S100A8","S100A9","VCAN","FCN1","ITGAX","HLA-DRA", "HLA-DQA1","HLA-DQB1")

#genes <- c(genes, "CD200R1","CD200R1L","RAMP1","CALCRL","CALCA","CALCB")

VlnPlot(ref.copy, features = genes, stack = TRUE, cols = palette, flip = TRUE, fill.by = "ident")

ggsave("plots/DC_annotated_violins.pdf", height=8, width=6)
```

Try with gene expression smoothing
```{r fig.height=5, fig.width=3}
obj <- ref.copy

expr <- Seurat::GetAssayData(obj, assay="RNA", slot="data")[genes,]
expr <- as.data.frame(t(as.matrix(expr)))

obj <- AddMetaData(obj, metadata=expr)

obj <- SmoothKNN(obj, signature.names=genes,
                           reduction="pca", k=20, suffix = "_smooth")

VlnPlot(obj, features = paste0(genes,"_smooth"), stack = TRUE, flip=TRUE,
        fill.by = "ident", cols = ref@misc$atlas.palette)
ggsave("plots/DC_annotated_violins_smooth.pdf", height=8, width=6)
```

Subset composition
```{r}
tab <- table(ref$Study, ref$functional.cluster)
tab.norm <- tab/rowSums(tab)

df <- reshape2::melt(tab.norm)
colnames(df) <- c("Study","Subtype","Frequency")

palette <- ref@misc$atlas.palette

ggplot(df, aes(x = Study, y = Frequency, 
            fill = Subtype)) + geom_bar(stat = "identity") + 
            theme_bw() + scale_fill_manual(values = palette) +
            theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
ggsave("plots/DC_composition_by_dataset.pdf", height=4, width=5)
```

Make a subset vs. study heatmap of pseudobulk profiles
```{r}
make.heatmap <- function(data, assay="RNA", genes, scale="row",
                         method=c("ward.D2", "average"), brewer.palette="RdBu",
                         cluster.col = "functional.cluster", flip=FALSE,
                         cluster_genes = FALSE, cluster_samples=FALSE, min.cells = 10,
                         palette = NULL) {
  
  require(pheatmap)
  set.seed(123)
  
  method = method[1]
  
  data$Study_Subset <- factor(paste(data@meta.data[,cluster.col],data$Study,sep="."))
  
  t <- table(data$Study_Subset)
  accept <- names(t)[t>min.cells]
  
  data <- subset(data, subset=Study_Subset %in% accept)
   
  #Calculate mean expression by cluster
  m <- c()
  for( g in unique(genes)){
    m[[g]] <- tapply(data@assays[[assay]][g,],data$Study_Subset, mean)
  }
  m <- as.data.frame(m)
  
  m <- m[accept,]
  
  m.study <- factor(unlist(lapply(strsplit(rownames(m),"\\.",perl = T),function(x) x[[2]])))
  m.subset <- factor(unlist(lapply(strsplit(rownames(m),"\\.",perl = T),function(x) x[[1]])))

  #gaps_col <- (which(!duplicated(m.subset))-1)[-1]
  
  breaksList = seq(-2, 2, by = 0.1)
  
  require(RColorBrewer)
  color = colorRampPalette(rev(brewer.pal(n = 7, name = brewer.palette)))(length(breaksList))
  
  if (is.null(palette)) {
    palette = brewer.pal(n=length(unique(m.subset)), name="Paired")
    names(palette) <- unique(m.subset)
  }
  
  annotation_col = data.frame(
                    Subtype = m.subset,
                    Study = m.study
                )
  rownames(annotation_col) = rownames(m)


  if (flip) { 
    h <- pheatmap::pheatmap(m, cluster_rows = cluster_samples,
                            cluster_cols = cluster_genes,scale = scale,
                            breaks = breaksList, color=color, 
                            annotation_row = annotation_col, 
                            show_rownames = F,
                            border_color = NA,
                            annotation_colors = list(Subtype=palette), 
                            fontsize_row=6,fontsize = 7, 
                            clustering_method=method)
  } else {
    h <- pheatmap::pheatmap(t(m),cluster_rows = cluster_genes,
                            cluster_cols = cluster_samples,scale = scale,
                            breaks = breaksList, color=color, 
                            annotation_col = annotation_col, 
                            show_colnames = F,
                            border_color = NA,
                            annotation_colors = list(Subtype=palette), 
                            fontsize_row=6,fontsize = 7, 
                            clustering_method=method)
  }
  return(h)
}
```

Plot heatmap of pseudo-bulk by subtype/study
```{r}
library(pheatmap)
h <- make.heatmap(ref.copy, assay = "RNA", genes = genes.use, min.cells=15,
            palette=palette, cluster_genes = FALSE, cluster_samples = FALSE)

ggsave("plots/DC_heatmap_pseudobulk_unclustered.pdf", plot=h, height=6, width=9)

h <- make.heatmap(ref.copy, assay = "RNA", genes = genes.use, min.cells=20,
            palette=palette, cluster_genes = TRUE, cluster_samples = TRUE)
ggsave("plots/DC_heatmap_pseudobulk_clustered.pdf", plot=h, height=7, width=10)
```
