---
title: "Integrate DC datasets - exclude T cell doublets"
author: "Massimo Andreatta & Santiago Carmona"
#output: html_notebook
---

```{r}
renv::restore()
```

Libraries
```{r}
library(ggplot2)
library(Seurat)
library(tidyr)
library(SeuratObject)
library(Matrix)
library(patchwork)
library(remotes)
library(UCell)
library(ProjecTILs)
```

Read in annotated reference map
```{r}
pdir <- "~/Dropbox/CSI/Datasets/Gerhard_JEM"
ref <- readRDS(paste0(pdir,"/DC_reference_v0.1.rds"))
```


```{r}
pdir <- "~/Dropbox/CSI/Datasets/Gerhard_JEM"

dataset.list <- readRDS(sprintf("%s/Gerhard_metanalysis_seuratlist.DC.anno.rds",pdir))

brown <- dataset.list$brownSpleen

DimPlot(brown, group.by = "state")
DimPlot(brown, group.by = "scGate_multi")
```

```{r}
brown.projected <- Run.ProjecTILs(brown, ref=ref, filter.cells = FALSE)
```



```{r fig.height=3.5, fig.width=10}
celltypes <- unique(brown.projected$state)
pll <- list()

for (c in celltypes) {
  sub <- subset(brown.projected, subset=state==c)
  pll[[c]] <- plot.projection(ref, query=sub, linesize = 0.5, pointsize = 0.5) + ggtitle(c)
}

wrap_plots(pll, ncol=4)
ggsave("plots/Brown_projected_bysubtype.noTcells.png", height=9, width=22)
```


Composition
```{r}
plot.statepred.composition(ref=ref, query=brown.projected)
ggsave("plots/Brown_projected_composition.noTcells.png", height=3.5, width=5)
```


Profile agreement
```{r fig.height=4}
genes4radar <- c("CLEC9A","XCR1","CADM1","CLEC10A","CD1C","CD1A",
                 "LAMP3","CCR7","FSCN1","S100A8","S100A9","VCAN","FCN1",
                 "GZMB","LILRA4","TCF4","PPP1R14A","AXL","PRDM16","ACY3")

plot.states.radar(ref, query=brown.projected, genes4radar = genes4radar, min.cells = 10)
ggsave("plots/Brown_projected_radar.noTcells.png", height=10, width=14)
```


#How about mouse data?
```{r}
library(scRNAseq)

sce <- ZilionisLungData('mouse')

counts <- Matrix::Matrix(counts(sce),sparse = TRUE)
meta <- colData(sce)

seurat <- CreateSeuratObject(counts)
seurat <- AddMetaData(seurat, metadata = as.data.frame(meta))
```


```{r fig.width=6}
seurat <- seurat |> NormalizeData() |> FindVariableFeatures(nfeatures=1000) |>
  ScaleData() |>  RunPCA(npcs=20) |> RunUMAP(dims=1:20)

a <- DimPlot(seurat, group.by="Major.cell.type") + theme(aspect.ratio = 1)
b <- DimPlot(seurat, group.by="Minor.subset") + theme(aspect.ratio = 1)
a | b
```

Classifier in original space
```{r fig.width=6}
zilionis <- ProjecTILs.classifier(seurat, ref=ref, filter.cells = TRUE, ncores=8)

a <- DimPlot(zilionis , group.by="Major.cell.type") + theme(aspect.ratio = 1)
b <-  DimPlot(zilionis , group.by="functional.cluster") + theme(aspect.ratio = 1)
a | b
```

Projection in reference space
```{r}
zilionis.proj <- Run.ProjecTILs(seurat, ref=ref, filter.cells = TRUE, ncores=8)
plot.projection(ref=ref, query=zilionis.proj)
```

```{r fig.height=3.5, fig.width=10}
celltypes <- unique(seurat$Minor.subset)
celltypes <- grep('DC', celltypes, value=T)
pll <- list()

for (c in celltypes) {
  sub <- subset(zilionis.proj, subset=Minor.subset==c)
  pll[[c]] <- plot.projection(ref, query=sub, linesize = 0.5, pointsize = 0.5) + ggtitle(c)
}

wrap_plots(pll, ncol=4)
```

Profile agreement
```{r fig.height=4}
genes4radar <- c("CLEC9A","XCR1","CADM1","CLEC10A","CD1C","CD1A",
                 "LAMP3","CCR7","FSCN1","S100A8","S100A9","VCAN","FCN1",
                 "GZMB","TSPAN13","TCF4","PPP1R14A","AXL","PRDM16","ACY3")

plot.states.radar(ref, query=zilionis.proj, genes4radar = genes4radar, min.cells = 10)
```
