---
title: "Load all datasets in Gerhard et al. metanalysis, and convert to Seurat"
author: "Massimo Andreatta & Santiago Carmona"
#output: html_notebook
---

```{r}
renv::restore()
```

Libraries
```{r}
library(ggplot2)
library(Seurat)
library(tidyr)
library(SeuratObject)
library(Matrix)
library(patchwork)
```

#NB: for conversion between Scanpy format to matrix files, see export_data.py script

Read in data for individual studies
```{r}
pdir <- "~/Dropbox/CSI/Datasets/Gerhard_JEM"
ddir <- "~/Dropbox/CSI/Datasets/Gerhard_JEM/exported"

studies <- list.dirs(path=ddir, full.names = FALSE)
studies <- studies[nchar(studies)>0]

names <- gsub("_\\S+","",studies, perl=T)

seurat.list <- list()

for (i in seq_along(studies)) {
  s = studies[i]
  proj = names[i]
   
  data <- t(readMM(file = sprintf("%s/%s/matrix.mtx", ddir, s)))

  cell.names <- read.table(sprintf("%s/%s/barcodes.tsv", ddir, s), sep="\t", header=T)[,1]
  gene.names <- read.table(sprintf("%s/%s/genes.tsv", ddir, s), sep="\t", header=T)[,1]
  meta <- read.table(sprintf("%s/%s/metadata.csv",ddir,s), sep=",",header=T)[,-1]
  rownames(meta) <- cell.names
  rownames(data) <- gene.names
  colnames(data) <- cell.names 
   
  seurat.list[[proj]] <- CreateSeuratObject(counts=data, project=proj, assay="RNA", meta.data = meta)

}

##And save the list of object to disk

saveRDS(seurat.list, file="Gerhard_metanalysis_seuratlist.rds")
saveRDS(seurat.list, file=sprintf("%s/Gerhard_metanalysis_seuratlist.rds",pdir))
```



Basic exploration of data
```{r}
plots <- list()

ndim=30
for (i in seq_along(seurat.list)) {
  s = names(seurat.list)[i]
  
  obj <- seurat.list[[s]]
  #obj <- NormalizeData(obj)  already normalized?
  
  obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
  obj <- ScaleData(obj, do.scale = TRUE, do.center = TRUE, verbose = F) 
  obj <- RunPCA(object = obj, features = obj@assays$RNA@var.features, npcs = ndim, verbose = F)
  
  obj <- RunUMAP(obj, reduction = "pca", dims = 1:ndim, seed.use=123, verbose = F)
  plots[[s]] <- DimPlot(obj, reduction = "umap", group.by = "state", label = T) + ggtitle(s) + NoLegend() +
             theme(axis.title=element_blank(),axis.text=element_blank(),axis.ticks=element_blank())
}
```

```{r fig.height=8, fig.width=16}
wrap_plots(plots, ncol=4)

ggsave("plots/Gerhard_sets_unsup_umap.pdf", width = 24, height=15)
```

