---
title: "Integrate DC datasets"
author: "Massimo Andreatta & Santiago Carmona"
#output: html_notebook
---

```{r}
renv::restore()
```

Libraries
```{r}
#remotes::install_github('carmonalab/UCell')
#remotes::install_github('carmonalab/STACAS')

library(ggplot2)
library(Seurat)
library(tidyr)
library(SeuratObject)
library(Matrix)
library(patchwork)
library(remotes)
library(UCell)
library(STACAS)
```

#NB: for conversion between Scanpy format to matrix files, see export_data.py script

Read in data as Seurat objects (see dc_analysis.Rmd for data conversion)
```{r}
pdir <- "~/Dropbox/CSI/Datasets/Gerhard_JEM"

seurat.list <- readRDS(sprintf("%s/Gerhard_metanalysis_seuratlist.DC.anno.rds",pdir))
```

See batch effects
```{r fig.height=3}
merged <- Reduce(merge, seurat.list)

merged <- FindVariableFeatures(merged, nfeatures = 1000)
merged <- merged %>% ScaleData() %>% RunPCA(npcs=20) %>% RunUMAP(dims=1:20)

library(RColorBrewer)
palette <- brewer.pal(n=5, name="Set3")
names(palette) <- c("cDC1","cDC2","DC3","pDC","Multi")

p1 <- DimPlot(merged, reduction="umap", group.by="Study") + theme(aspect.ratio = 1)
p2 <- DimPlot(merged, reduction="umap", group.by="scGate_multi", cols=palette) + theme(aspect.ratio = 1)
p1 | p2

ggsave("plots/Gerhard_sets_preintegration.pdf", height = 5, width=10)
```

Find anchors
```{r}
nfeatures=1000
ndim=30
stacas_anchors <- FindAnchors.STACAS(seurat.list, 
                                     anchor.features = nfeatures,
                                     dims = 1:ndim)
```

```{r}
tree <- SampleTree.STACAS(stacas_anchors,
                          obj.names = names(seurat.list),
                          hclust.method = "ward.D")
```

Integrate data
```{r}
object_integrated <- IntegrateData.STACAS(stacas_anchors,
                                          sample.tree=tree,
                                              dims=1:ndim)
```

Dimred
```{r}
object_integrated <- object_integrated %>% ScaleData() %>% RunPCA(npcs=ndim) %>% RunUMAP(dims=1:ndim)
```

```{r fig.height=3}
library(RColorBrewer)
palette <- brewer.pal(n=5, name="Set3")
names(palette) <- c("cDC1","cDC2","DC3","pDC","Multi")

p1 <- DimPlot(object_integrated, reduction="umap", group.by="Study") + theme(aspect.ratio = 1)
p2 <- DimPlot(object_integrated, reduction="umap", group.by="scGate_multi", cols=palette) + theme(aspect.ratio = 1)
p1 | p2

ggsave("plots/Gerhard_sets_STACAS_unsup.pdf", height = 5, width=10)
```

Where are specific subtypes, e.g. the "DC5" by Villani et al.?
```{r fig.height=3}
p <- list()
p[[1]] <- DimPlot(object_integrated, reduction = "umap", cells.highlight = which(object_integrated$state == "vi-DC5")) + 
  theme(aspect.ratio = 1) + NoLegend() + ggtitle("Villani DC5")
p[[2]] <- DimPlot(object_integrated, reduction = "umap", cells.highlight = which(object_integrated$state == "brS-AS DC")) + 
  theme(aspect.ratio = 1) +NoLegend() + ggtitle("brS AS-DC")
p[[3]] <- DimPlot(object_integrated, reduction = "umap", cells.highlight = which(object_integrated$state == "vi-DC6")) +
  theme(aspect.ratio = 1) + NoLegend() + ggtitle("Villani DC6")
p[[4]] <- DimPlot(object_integrated, reduction = "umap", cells.highlight = which(object_integrated$state == "zi-tpDC")) +
  theme(aspect.ratio = 1) + NoLegend() + ggtitle("Zilionis pDCs")


wrap_plots(p)
```

Unsupervised clustering
```{r}
k.param <- 20
res <- 0.3

object_integrated <- FindNeighbors(object_integrated, k.param=k.param)
object_integrated <- FindClusters(object_integrated, resolution = res)

DimPlot(object_integrated, reduction = "umap", group.by="seurat_clusters") + theme(aspect.ratio = 1)
```

Find markers for unsupervised clusters
```{r}
Idents(object_integrated) <- "seurat_clusters"
DefaultAssay(object_integrated) <- "RNA"

set.seed(1234)
cluster.markers <- FindAllMarkers(object_integrated, only.pos = T, min.pct = 0.1, min.diff.pct=0.1, 
                                  logfc.threshold = 0.25, max.cells.per.ident = 500, test.use="wilcox",base=exp(1))

all <- cluster.markers |> dplyr::group_by(cluster) |> dplyr::top_n(n = 50, wt = abs(avg_logFC))

for (i in levels(object_integrated@active.ident)) {
    print(subset(all, cluster==i))
}  
DefaultAssay(object_integrated) <- "integrated"

```

```{r fig.height=3}
DefaultAssay(object_integrated) <- "RNA"

FeaturePlot(object_integrated, features=c("CLEC10A","IL1R2","CD1C","CFP"))
FeaturePlot(object_integrated, features=c("C1QA","C1QB","C1QC","FCGR2A"))
FeaturePlot(object_integrated, features=c("CD1A","CD207","FCGBP","S100B"))
FeaturePlot(object_integrated, features=c("S100A8","S100A9","FCN1","CD14"))
FeaturePlot(object_integrated, features=c("LTB","RUNX3","AXL","IL22RA2"))

```
